version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - redis:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  redis:
    driver: local
